#!/usr/bin/env bash
# Install nighttrade as macOS launchd services.
#
# Creates two user LaunchAgents that start on login, restart on crash, and
# keep running with no terminal open:
#   * com.nighttrade.observer   — the 24/7 live S&P 500 observer
#   * com.nighttrade.dashboard  — the FastAPI dashboard on 127.0.0.1:<port>
#
# Usage:  deploy/install.sh [port]      (port defaults to 8001)
#
# Paper / observation only — this never places a real trade.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="/usr/bin/python3"
AGENTS="$HOME/Library/LaunchAgents"
PORT="${1:-8001}"
WRAPPER="$REPO/deploy/_svc-run.sh"
U="$(id -u)"

echo "nighttrade deploy"
echo "  repo : $REPO"
echo "  port : $PORT"

# Sanity check: the package and its deps must import.
if ! "$PY" -c "import nighttrade, fastapi, uvicorn, yfinance" 2>/dev/null; then
  echo "ERROR: nighttrade is not importable by $PY." >&2
  echo "Run first:  python3 -m pip install -e \".[dev,online]\"" >&2
  exit 1
fi

mkdir -p "$AGENTS" "$REPO/logs"

# A launchd-invoked wrapper that pins a known-good environment. launchd does
# not reliably pass HOME (needed to find the user site-packages) or PYTHONPATH,
# so we bake them in here rather than depending on the plist environment.
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Generated by deploy/install.sh — pins the environment for launchd services.
export HOME="$HOME"
export PYTHONPATH="$REPO/src"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
cd "$REPO" || exit 1
exec "\$@"
EOF
chmod +x "$WRAPPER"

# Stop anything already running outside launchd.
pkill -f 'nighttrade observe' 2>/dev/null || true
pkill -f 'nighttrade dashboard' 2>/dev/null || true
sleep 1

make_plist() {
  # Usage: make_plist <label> [--throttle SECONDS] <cmd...>
  local label="$1"; shift
  local throttle=20
  if [ "${1:-}" = "--throttle" ]; then
    throttle="$2"
    shift 2
  fi
  local plist="$AGENTS/$label.plist"
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"' \
         '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    echo '<plist version="1.0"><dict>'
    echo "  <key>Label</key><string>$label</string>"
    echo '  <key>ProgramArguments</key><array>'
    echo '    <string>/bin/bash</string>'
    echo "    <string>$WRAPPER</string>"
    for arg in "$@"; do echo "    <string>$arg</string>"; done
    echo '  </array>'
    echo "  <key>WorkingDirectory</key><string>$REPO</string>"
    echo '  <key>RunAtLoad</key><true/>'
    echo '  <key>KeepAlive</key><true/>'
    echo "  <key>ThrottleInterval</key><integer>$throttle</integer>"
    echo "  <key>StandardOutPath</key><string>$REPO/logs/$label.out.log</string>"
    echo "  <key>StandardErrorPath</key><string>$REPO/logs/$label.err.log</string>"
    echo '</dict></plist>'
  } > "$plist"
  launchctl bootout "gui/$U/$label" 2>/dev/null || true
  # Give launchd time to fully tear down the old job before bootstrapping
  # the new one. A 1s settle raced on rapid re-deploys -> "Bootstrap
  # failed: 5: Input/output error" (observed 2026-06-03). Retry once.
  sleep 2
  if ! launchctl bootstrap "gui/$U" "$plist" 2>/dev/null; then
    sleep 3
    launchctl bootstrap "gui/$U" "$plist" 2>/dev/null || \
      echo "  WARN: bootstrap $label failed twice — kickstart will recover it"
  fi
  echo "  loaded $label"
}

# The observer runs under `caffeinate -s` so the Mac will not system-sleep
# while the bot is alive (needed for round-the-clock tracking).
make_plist com.nighttrade.observer \
  /usr/bin/caffeinate -s "$PY" -m nighttrade observe --live --interval 200

# Dashboard binds to 0.0.0.0 (always-bindable) and enforces tailnet-only
# access at the application layer via TailnetOnlyMiddleware. Previously
# this script wired the Tailscale IP directly into --host, which coupled
# service liveness to Tailscale interface state — a momentary flap during
# deploy/sync.sh (observed 2026-06-02) parked the service in launchd
# throttle backoff. ThrottleInterval bumped to 120s for the same reason:
# gives any transient network reshape room to settle before launchd gives up.
make_plist com.nighttrade.dashboard \
  --throttle 120 \
  "$PY" -m nighttrade dashboard --host 0.0.0.0 --port "$PORT"

# Periodic watchdog — different semantics from observer/dashboard so it
# can't use make_plist (which sets KeepAlive=true). This one uses
# StartInterval=300 so launchd fires it every 5 minutes; the script
# itself exits quickly each run after doing its health check.
WATCHDOG_LABEL="com.nighttrade.watchdog"
WATCHDOG_PLIST="$AGENTS/$WATCHDOG_LABEL.plist"
{
  echo '<?xml version="1.0" encoding="UTF-8"?>'
  echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"' \
       '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
  echo '<plist version="1.0"><dict>'
  echo "  <key>Label</key><string>$WATCHDOG_LABEL</string>"
  echo '  <key>ProgramArguments</key><array>'
  echo '    <string>/bin/bash</string>'
  echo "    <string>$REPO/deploy/watchdog.sh</string>"
  echo '  </array>'
  echo "  <key>WorkingDirectory</key><string>$REPO</string>"
  echo '  <key>RunAtLoad</key><true/>'
  echo '  <key>StartInterval</key><integer>300</integer>'
  echo "  <key>StandardOutPath</key><string>$REPO/logs/$WATCHDOG_LABEL.out.log</string>"
  echo "  <key>StandardErrorPath</key><string>$REPO/logs/$WATCHDOG_LABEL.err.log</string>"
  echo '</dict></plist>'
} > "$WATCHDOG_PLIST"
launchctl bootout "gui/$U/$WATCHDOG_LABEL" 2>/dev/null || true
sleep 1
launchctl bootstrap "gui/$U" "$WATCHDOG_PLIST"
echo "  loaded $WATCHDOG_LABEL  (fires every 300s, kicks observer + dashboard if down)"

# RunAtLoad does not reliably fire on bootstrap in the gui/ domain
# (observed 2026-06-03 — jobs loaded with the process never spawning until
# kickstarted). Force-kick the long-running services so a bare install.sh
# run actually starts them, not just sync.sh. Without this, an install run
# (e.g. during deploy recovery) leaves the observer loaded-but-dead.
sleep 1
for svc in com.nighttrade.observer com.nighttrade.dashboard; do
  launchctl kickstart "gui/$U/$svc" >/dev/null 2>&1 || true
done
echo "  kickstarted observer + dashboard"

echo
echo "Done. The observer + dashboard now run as background services."
TS_BIN="$(command -v tailscale 2>/dev/null || echo /usr/local/bin/tailscale)"
TS_IP="$("$TS_BIN" ip -4 2>/dev/null | head -1 || true)"
if [ -n "$TS_IP" ]; then
  echo "  dashboard : bound to 0.0.0.0:$PORT, tailnet-only access enforced by middleware"
  echo "              reachable from tailnet at $TS_IP:$PORT"
else
  echo "  dashboard : bound to 0.0.0.0:$PORT (Tailscale not detected — local only via middleware)"
fi
echo "  logs      : $REPO/logs/com.nighttrade.*.log"
echo "  manage    : launchctl list | grep nighttrade"
if [ -n "$TS_IP" ]; then
  TS_HOST="$("$TS_BIN" status --json 2>/dev/null \
    | "$PY" -c 'import sys,json; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' \
    2>/dev/null || true)"
  echo
  echo "Open from any device on your tailnet:"
  [ -n "$TS_HOST" ] && echo "  http://$TS_HOST:$PORT"
  echo "  http://$TS_IP:$PORT"
fi
