#!/usr/bin/env bash
# Install nighttrade as macOS launchd services.
#
# Creates two user LaunchAgents that start on login, restart on crash, and
# keep running with no terminal open:
#   * com.nighttrade.observer   — the 24/7 live S&P 500 observer
#   * com.nighttrade.dashboard  — the FastAPI dashboard on 127.0.0.1:<port>
#
# Usage:  deploy/install.sh [port]      (port defaults to 8001)
#
# Paper / observation only — this never places a real trade.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="/usr/bin/python3"
AGENTS="$HOME/Library/LaunchAgents"
PORT="${1:-8001}"
WRAPPER="$REPO/deploy/_svc-run.sh"
U="$(id -u)"

echo "nighttrade deploy"
echo "  repo : $REPO"
echo "  port : $PORT"

# Sanity check: the package and its deps must import.
if ! "$PY" -c "import nighttrade, fastapi, uvicorn, yfinance" 2>/dev/null; then
  echo "ERROR: nighttrade is not importable by $PY." >&2
  echo "Run first:  python3 -m pip install -e \".[dev,online]\"" >&2
  exit 1
fi

mkdir -p "$AGENTS" "$REPO/logs"

# A launchd-invoked wrapper that pins a known-good environment. launchd does
# not reliably pass HOME (needed to find the user site-packages) or PYTHONPATH,
# so we bake them in here rather than depending on the plist environment.
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Generated by deploy/install.sh — pins the environment for launchd services.
export HOME="$HOME"
export PYTHONPATH="$REPO/src"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
cd "$REPO" || exit 1
exec "\$@"
EOF
chmod +x "$WRAPPER"

# Stop anything already running outside launchd.
pkill -f 'nighttrade observe' 2>/dev/null || true
pkill -f 'nighttrade dashboard' 2>/dev/null || true
sleep 1

make_plist() {
  # Usage: make_plist <label> [--throttle SECONDS] <cmd...>
  local label="$1"; shift
  local throttle=20
  if [ "${1:-}" = "--throttle" ]; then
    throttle="$2"
    shift 2
  fi
  local plist="$AGENTS/$label.plist"
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"' \
         '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    echo '<plist version="1.0"><dict>'
    echo "  <key>Label</key><string>$label</string>"
    echo '  <key>ProgramArguments</key><array>'
    echo '    <string>/bin/bash</string>'
    echo "    <string>$WRAPPER</string>"
    for arg in "$@"; do echo "    <string>$arg</string>"; done
    echo '  </array>'
    echo "  <key>WorkingDirectory</key><string>$REPO</string>"
    echo '  <key>RunAtLoad</key><true/>'
    echo '  <key>KeepAlive</key><true/>'
    echo "  <key>ThrottleInterval</key><integer>$throttle</integer>"
    echo "  <key>StandardOutPath</key><string>$REPO/logs/$label.out.log</string>"
    echo "  <key>StandardErrorPath</key><string>$REPO/logs/$label.err.log</string>"
    echo '</dict></plist>'
  } > "$plist"
  launchctl bootout "gui/$U/$label" 2>/dev/null || true
  sleep 1
  launchctl bootstrap "gui/$U" "$plist"
  echo "  loaded $label"
}

# The observer runs under `caffeinate -s` so the Mac will not system-sleep
# while the bot is alive (needed for round-the-clock tracking).
make_plist com.nighttrade.observer \
  /usr/bin/caffeinate -s "$PY" -m nighttrade observe --live --interval 200

# Dashboard binds to 0.0.0.0 (always-bindable) and enforces tailnet-only
# access at the application layer via TailnetOnlyMiddleware. Previously
# this script wired the Tailscale IP directly into --host, which coupled
# service liveness to Tailscale interface state — a momentary flap during
# deploy/sync.sh (observed 2026-06-02) parked the service in launchd
# throttle backoff. ThrottleInterval bumped to 120s for the same reason:
# gives any transient network reshape room to settle before launchd gives up.
make_plist com.nighttrade.dashboard \
  --throttle 120 \
  "$PY" -m nighttrade dashboard --host 0.0.0.0 --port "$PORT"

echo
echo "Done. The observer + dashboard now run as background services."
TS_BIN="$(command -v tailscale 2>/dev/null || echo /usr/local/bin/tailscale)"
TS_IP="$("$TS_BIN" ip -4 2>/dev/null | head -1 || true)"
if [ -n "$TS_IP" ]; then
  echo "  dashboard : bound to 0.0.0.0:$PORT, tailnet-only access enforced by middleware"
  echo "              reachable from tailnet at $TS_IP:$PORT"
else
  echo "  dashboard : bound to 0.0.0.0:$PORT (Tailscale not detected — local only via middleware)"
fi
echo "  logs      : $REPO/logs/com.nighttrade.*.log"
echo "  manage    : launchctl list | grep nighttrade"
if [ -n "$TS_IP" ]; then
  TS_HOST="$("$TS_BIN" status --json 2>/dev/null \
    | "$PY" -c 'import sys,json; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' \
    2>/dev/null || true)"
  echo
  echo "Open from any device on your tailnet:"
  [ -n "$TS_HOST" ] && echo "  http://$TS_HOST:$PORT"
  echo "  http://$TS_IP:$PORT"
fi
